name:                postgresql-client
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- datetime >= 0.3.1 && < 0.4.0
- network-simple >= 0.4.5 && < 0.5.0
- mtl >= 2.2.2 && < 3.0.0
- transformers >= 0.5.6.2 && < 0.6.0.0
- text >= 1.2.4.0 && < 1.3.0.0

library:
  source-dirs: src
  dependencies:
  - datetime >= 0.3.1 && < 0.4.0
  - template-haskell >= 2.15.0.0 && < 2.16.0.0
  - bytestring >= 0.10.0.0 && < 0.12.0.0
  - bytestring-conversion >= 0.3.1 && < 0.4.0
  - cryptohash-md5 >= 0.11.100.1 && < 0.12.0.0
  - base64 >= 0.4.2.2 && < 0.5.0.0
  - hexstring >= 0.11.1 && < 0.12.0

executables:
  postgresql-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postgresql-client

tests:
  postgresql-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postgresql-client
